services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    networks:
      - db-stack
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_AUTO_UPGRADE: '1'
    ports:
      - 3306:3306
    volumes:
      - /mnt/nfsshare/mariadb/data:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    networks:
      - db-stack
    ports:
      - 27017:27017
    volumes:
      - /mnt/nfsshare/mongo/data:/data/db
      - /mnt/nfsshare/mongo/config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    deploy:
      mode: replicated
      replicas: 1

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    networks:
      - db-stack
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    deploy:
      mode: replicated
      replicas: 1

  minio:
    image: minio/minio:latest
    container_name: minio
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - db-stack
    volumes:
      - /mnt/nfsshare/minio/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: pgvector/pgvector:pg17 # PostgreSQL with pgvector support
    container_name: pgvector
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - db-stack
    ports:
      - 5432:5432
    volumes:
      - mnt/nfsshare/postgres:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - db-stack
    deploy:
      mode: replicated
      replicas: 1

networks:
  db-stack:
    driver: overlay
    attachable: true
