---
- name: Infrastructure Discovery
  hosts: all
  gather_facts: true
  collections:
    - wolskinet.infrastructure

  tasks:
    - name: Run infrastructure discovery
      ansible.builtin.include_role:
        name: discovery
