# Final Release Testing Inventory
# Generated by Terraform - do not edit manually

[all:vars]
ansible_user=ed
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

# Server VMs - focused on production configuration
[servers]
%{ for name, vm in vms ~}
%{ if vm.test_type == "server" ~}
${name} ansible_host=${vm.ip_address} ansible_distribution=${vm.os_family}
%{ endif ~}
%{ endfor ~}

# Workstation VMs - focused on development configuration
[workstations]
%{ for name, vm in vms ~}
%{ if vm.test_type == "workstation" ~}
${name} ansible_host=${vm.ip_address} ansible_distribution=${vm.os_family}
%{ endif ~}
%{ endfor ~}

# Platform groups for platform-specific testing
[ubuntu]
%{ for name, vm in vms ~}
%{ if vm.os_family == "Ubuntu" ~}
${name}
%{ endif ~}
%{ endfor ~}

[debian]
%{ for name, vm in vms ~}
%{ if vm.os_family == "Debian" ~}
${name}
%{ endif ~}
%{ endfor ~}

[archlinux]
%{ for name, vm in vms ~}
%{ if vm.os_family == "Archlinux" ~}
${name}
%{ endif ~}
%{ endfor ~}

# All test VMs
[test_vms:children]
servers
workstations
