#!/bin/bash
# Cleanup Phase III Expanded Linux VMs

echo "=== Phase III Expanded Linux VM Cleanup ==="

# Destroy via Terraform first
if [ -d terraform ]; then
    cd terraform
    echo "Step 1: Destroying VMs via OpenTofu..."
    tofu destroy -auto-approve 2>/dev/null || true
    rm -f inventory.ini
    cd ..
fi

# Manual cleanup in case terraform state is out of sync
echo "Step 2: Manual VM cleanup (if needed)..."
VM_NAMES="arch-workstation debian13-workstation ubuntu24-workstation debian12-server ubuntu22-server"

for vm in $VM_NAMES; do
    if LIBVIRT_DEFAULT_URI=qemu:///system virsh dominfo "$vm" >/dev/null 2>&1; then
        echo "  Cleaning up $vm..."
        LIBVIRT_DEFAULT_URI=qemu:///system virsh destroy "$vm" 2>/dev/null || true
        LIBVIRT_DEFAULT_URI=qemu:///system virsh undefine "$vm" 2>/dev/null || true
    fi
done

# Clean up storage pool if it exists
echo "Step 3: Cleaning up storage pool..."
if LIBVIRT_DEFAULT_URI=qemu:///system virsh pool-info phase3_vm_pool >/dev/null 2>&1; then
    echo "  Destroying storage pool phase3_vm_pool..."
    LIBVIRT_DEFAULT_URI=qemu:///system virsh pool-destroy phase3_vm_pool 2>/dev/null || true
    LIBVIRT_DEFAULT_URI=qemu:///system virsh pool-undefine phase3_vm_pool 2>/dev/null || true
fi

# Clean up host_vars generated by discovery
if [ -d terraform/host_vars ]; then
    rm -rf terraform/host_vars
fi

echo "✅ All VMs and generated files cleaned up"
echo ""
echo "=== Cleanup Complete ==="
