# SSH Configuration for Final Release Testing VMs
# Generated by Terraform - do not edit manually

%{ for name, vm in vms ~}
Host ${name}
    HostName ${vm.ip_address}
    User ed
    IdentityFile ~/.ssh/id_ed25519
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    LogLevel ERROR
    ConnectTimeout 10

%{ endfor ~}
