services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./ollama:/root/.ollama
    networks:
      - proxy
    ports:
      - "11434:11434" # Add this line to expose the port
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    restart: unless-stopped
    volumes:
      - ./open-webui:/app/backend/data
    depends_on:
      - ollama
    networks:
      - proxy
    # ports:
    #   - ${OPEN_WEBUI_PORT-3000}:8080  # Only need this if exposing to the network (vice proxy)
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - ENABLE_RAG_WEB_SEARCH=True
      - RAG_WEB_SEARCH_ENGINE=searxng
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      - SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>
      - TIKA_SERVER_URL=http://tika:9998
    extra_hosts:
      - host.docker.internal:host-gateway
  piplelines:
    image: ghcr.io/open-webui/pipelines:${WEBUI_DOCKER_TAG-main}
    container_name: pipelines
    restart: unless-stopped
    volumes:
      - ./pipelines:/app/pipelines
    depends_on:
      - open-webui
    networks:
      - proxy
    # ports:
    #   - ${PIPELINES_PORT-9099}:9099  # Only need this if exposing to the network (vice proxy)
    extra_hosts:
      - host.docker.internal:host-gateway
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    volumes:
      - ./searxng:/etc/searxng
    depends_on:
      - open-webui
    restart: unless-stopped
    networks:
      - proxy
    # ports:
    #   - "8888:8080" # Only need this if exposing to the network (vice proxy)

  # whisperx-api:
  #   image: pluja/whisperx-api:latest
  #   networks:
  #     - proxy
  #   ports:
  #     - "8088:8000"
  #   volumes:
  #     - ./data/uploads:/app/data
  #     - ./data/whisper_models:/app/wx_models
  #   environment:
  #     WHISPER_THREADS: 8
  #     WHISPER_DEVICE: cuda
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           count: all
  #           capabilities: [gpu]

networks:
  proxy:
    external: True
